  base_frame:  base_link
  odom_frame:  odom
  delta:  0.1
  xmin:  -5
  ymin:  -5
  xmax:  5
  ymax:  5
  maxUrange:  5
  map_update_interval:  0.1
  linearUpdate:  0.05
  angularUpdate:  0.05
  temporalUpdate:  0.1
  particles:  10