DWAPlannerROS:
 acc_lim_x: 1.5
 acc_lim_Y: 1.5
 acc_lim_th: 1
 max_trans_vel: 1
 min_trans_vel: 0.1
 max_vel_x: 0.5
 min_vel_x: -0.5
 max_vel_y: 0.15
 min_vel_y: -0.15
 max_rot_vel: 1
 min_rot_vel: 0.1
 xy_goal_tolerance: 1
 yaw_goal_tolerance: 1
 atch_xy_goal_tolerance: false

 sim_time: 1.7
 sim_granularity: 0.025
 vx_samples: 3
 vy_samples: 10
 vth_samples: 20
 controller_frequency: 20

 path_distance_bias: 32
 goal_distance_bias: 24
 occdist_scale: 0.1
 forward_point_distance: 0.5
 stop_time_buffer: 0.2
 scaling_speed: 0.25
 max_scaling_factor: 0.2
 oscillation_reset_dist: 0.5
 prune_plan: false
 