DWAPlannerROS:
 acc_lim_x: 0.5
 acc_lim_Y: 0.5
 acc_lim_th: 3
 max_trans_vel: 1
 min_trans_vel: -0.1
 max_vel_x: 2
 min_vel_x: -0.1
 max_vel_y: 2
 min_vel_y: -0.1
 max_rot_vel: 5
 min_rot_vel: -5
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.1
 atch_xy_goal_tolerance: false

 sim_time: 5.7
 sim_granularity: 0.025
 vx_samples: 10
 vy_samples: 10
 vth_samples: 10
 controller_frequency: 20

 path_distance_bias: 10
 goal_distance_bias: 10
 occdist_scale: 0.1
 forward_point_distance: 0.5
 stop_time_buffer: 0.2
 scaling_speed: 0.25
 max_scaling_factor: 0.2
 oscillation_reset_dist: 0.5
 prune_plan: false
 