global_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.5
  width: 5
  height: 5
  origin_x: -0.5
  origin_y: -0.5
  static_map: true
  rolling_window: false
  inflation_radius: 0.1
  resolution: 0.01

