# /robot:
/gazebo_ros_control:
  pid_gains:
    summit_xl_front_right_wheel_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    summit_xl_front_left_wheel_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    summit_xl_back_right_wheel_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    summit_xl_back_left_wheel_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    summit_xl_front_ptz_camera_pan_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    summit_xl_front_ptz_camera_tilt_joint:
      p: 100.0
      i: 0.01
      d: 0.0